spring:
  profiles: eureka-host2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-host2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-host1:8761/eureka/