spring:
  profiles: eureka-host1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-host1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-host2:8762/eureka/